[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = [
    "probe-rs", 
    "run", 
    "--chip",
    "nRF52833_xxAA",
    "--log-format",
    "{t} {L} {s}",
]

[build]
target = "thumbv7em-none-eabihf" 

[env]
DEFMT_LOG = "info"
